# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Release pipeline
on:
  push:
    branches:
      - 'master'
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with: # https://stackoverflow.com/a/65081720
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: "0"
      - name: Configure git
        run: |
          git config --global user.email "13139061+mikenabhan@users.noreply.github.com"
          git config --global user.name "Github Actions Pipeline"
      - name: Install auto
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.34.2/auto-linux.gz | gunzip > /usr/local/bin/auto && \
          chmod a+x /usr/local/bin/auto
      - name: Publish new version
        run: GH_TOKEN="${{ secrets.GITHUB_TOKEN }}" auto shipit
      # - id: version
      #   name: Output new version
      #   run: echo "::set-output name=version::$(poetry version -s)"

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Declare some variables
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "mikenabhan/country-recipe-finder:release-${{ steps.vars.outputs.sha_short }}"

